### ISSUE TITLE
安装用于浏览器的样式仅悄然失败

### ISSUE THREAD

**Issue by yfdyh000** [FirefoxBar/xStyle#20]
应该警告不适用。
例如 https://userstyles.org/styles/83431/minimal-floating-scrollbars-for-firefox-windows
仅 `uncaught exception: undefined`

**Comment by sylingd** [comment]
没办法进行警告。
例如链接中的这个样式，代码如下：
```css
/* 省略部分代码 */

scrollbar thumb:hover, scrollbar thumb:active
{
  background-color: rgba(0,0,0,0.5);
}

html div scrollbar
{
  -moz-margin-start: 0!important;
}
```

存在一些问题：
1.此代码包含部分用于正常HTML的代码
2.CSS中可能会包含一些非已知的元素，但不代表就不能使用。例如，`scrollbar`不一定就是浏览器本身的滚动条，页面也可以定义名为`scrollbar`的元素（即便`scrollbar`并不是标准的HTML元素）。还比如，某个元素是Chrome特有而Firefox没有的
