### ISSUE TITLE
關於 .user.css 格式

### ISSUE THREAD

**Issue by eight04** [FirefoxBar/xStyle#25]
8/6 時我在 openstyles/stylus [開了一個 PR](https://github.com/openstyles/stylus/pull/134) 實作 `.user.css` 格式（基本上就是 mozilla 格式 + metadata block） 。最近 stylus 的成員提到 xStyle 也有支援不同的格式，在 https://github.com/FirefoxBar/xStyle/issues/12 裡也有提到 `.user.css`，所以想說是否要交換一下意見。#12 裡提到的已經開始實作了嗎？

如果要測試的話，可以安裝 https://github.com/eight04/stylus/tree/dev-user-css 後，進入 https://gist.githubusercontent.com/eight04/1b9edeb170d9f8bbabfb06dc6627f8f7/raw/foo.user.css ，就會看到特殊的安裝介面了。

**Comment by sylingd** [comment]
已经在2.0.0版本中实现了。很多细节也不一样

**Comment by sylingd** [comment]
具体解释：
1.因CSS本身已经支持变量（见[此样式](https://userstyles.org/styles/124770/tieba-maverick)）故xStyle未做实现。
2.为了和原版在一定程度上保持一致性，没有使用namespace区分不同样式，而是使用homepageURL区分。即便主页一样，也需要给URL加参数来保证xStyle会识别为不同样式
3.使用md5来验证是否为最新版，而不是语义化版本号（semver）原因同上
4.高级选项功能基本和userstyles.org保持一致，方便迁移

**Comment by eight04** [comment]
我主要的目的是讓 Stylus 也能支援 xStyle 的 usercss。如果 xStyle 想實作 Stylus 的 usercss 格式我也可以幫忙。

> 因var存在歧义，故xStyle使用的是advanced

xStyle 的 `@var` 有別的用途嗎？

我看了 [文件](https://github.com/FirefoxBar/xStyle/wiki/%E5%9C%A8%E6%A0%B7%E5%BC%8F%E4%B8%AD%E4%BD%BF%E7%94%A8%E9%AB%98%E7%BA%A7%E9%80%89%E9%A1%B9)，color 和 text 和 Stylus 是相同的，下面是比較不瞭解的地方︰
```
@advanced dropdown browser "Your browser" {
	fx "Firefox" <<<EOT
color: red; EOT;
	cr "Chrome" <<<EOT
color: green; EOT;
}
```
這是一個 `<select>`。`"Firefox"` 和 `"Chrome"` 看起來是 `<option>`，而`<<<EOR ... EOT;` 中的內容是值。那 `fx` 跟 `cr` 的用途是？
```
@advanced image background "Page background" {
	bg_1 "Background 1" "http://example.com/example.jpg"
	bg_2 "Background 2" "http://example.com/photo.php?id=_A_IMAGE_ID_"
}
```
image 也是，多了 `bg_1`, `bg_2` 兩個值。

另外有範例可以試試嗎？或是有人已經上傳這種格式的連結也可以。我試了把下面的檔案存成 .user.css 後以 manage.html 內的 install from file 安裝，雖然 metadata 被移除了，但好像沒效果︰
```css
/* ==UserStyle==
@name test
@advanced color font-color 'Font color' #123456
@advanced text nav-height 'Navbar height' 60px
==/UserStyle== */

@-moz-document domain("stackoverflow.com") {
	body {
		color: /*[[font-color]]*/;
		background: whitesmoke;
	}
	body > header {
		height: /*[[nav-height]]*/!important;
	}
}
```
xStyle 2.0.9
